# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagesMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_type', models.PositiveSmallIntegerField(choices=[(10, 'Hindi'), (20, 'Marathi'), (40, 'Telugu'), (80, 'Malyalam'), (100, 'Konkani')], db_index=True)),
                ('root_w', models.CharField(max_length=255, unique=True)),
                ('mapping', models.ManyToManyField(related_name='_languagesmapping_mapping_+', to='mapping.LanguagesMapping')),
            ],
        ),
    ]
