# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_LANGUAGE_MAPPPING'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagesmapping',
            name='root_w',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='languagesmapping',
            unique_together=set([('root_w', 'lang_type')]),
        ),
    ]
